In [1]:
a = 1
print(a)

1


In [2]:
b = 1.0
print(b)

1.0


In [3]:
c = 1 + 0j
print(c)

(1+0j)


In [4]:
d = "1"
print(d)

1


In [5]:
print(a, b, c, d)

1 1.0 (1+0j) 1


In [6]:
print(type(d))
print(dir(d))

<class 'str'>
['__add__', '__class__', '__contains__', '__delattr__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__getnewargs__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__iter__', '__le__', '__len__', '__lt__', '__mod__', '__mul__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__rmod__', '__rmul__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', 'capitalize', 'casefold', 'center', 'count', 'encode', 'endswith', 'expandtabs', 'find', 'format', 'format_map', 'index', 'isalnum', 'isalpha', 'isascii', 'isdecimal', 'isdigit', 'isidentifier', 'islower', 'isnumeric', 'isprintable', 'isspace', 'istitle', 'isupper', 'join', 'ljust', 'lower', 'lstrip', 'maketrans', 'partition', 'replace', 'rfind', 'rindex', 'rjust', 'rpartition', 'rsplit', 'rstrip', 'split', 'splitlines', 'startswith', 'strip', 'swapcase', 'title', 'translate', 'upper', 'zfill']


In [8]:
print(type(a))

<class 'int'>


In [10]:
print(type(a))
print(dir(a))

<class 'int'>
['__abs__', '__add__', '__and__', '__bool__', '__ceil__', '__class__', '__delattr__', '__dir__', '__divmod__', '__doc__', '__eq__', '__float__', '__floor__', '__floordiv__', '__format__', '__ge__', '__getattribute__', '__getnewargs__', '__gt__', '__hash__', '__index__', '__init__', '__init_subclass__', '__int__', '__invert__', '__le__', '__lshift__', '__lt__', '__mod__', '__mul__', '__ne__', '__neg__', '__new__', '__or__', '__pos__', '__pow__', '__radd__', '__rand__', '__rdivmod__', '__reduce__', '__reduce_ex__', '__repr__', '__rfloordiv__', '__rlshift__', '__rmod__', '__rmul__', '__ror__', '__round__', '__rpow__', '__rrshift__', '__rshift__', '__rsub__', '__rtruediv__', '__rxor__', '__setattr__', '__sizeof__', '__str__', '__sub__', '__subclasshook__', '__truediv__', '__trunc__', '__xor__', 'bit_length', 'conjugate', 'denominator', 'from_bytes', 'imag', 'numerator', 'real', 'to_bytes']


In [15]:
s = "Hello World"
print(s.lower())
print(s.upper())
print(s.replace(" " , ", "))

hello world
HELLO WORLD
Hello, World


In [20]:
f = s.split()
print(f[0], f[1])
print(f[1])

Hello World
World


In [19]:
a = "1"
print(a.zfill(3))

001


In [25]:
a = 1
b = 1.0
c = 1 + 0j
d = "1"

minha_lista = [a, b, c, d]

print(minha_lista)
print(minha_lista[0], minha_lista[1], minha_lista[2], minha_lista[3])
print(type(minha_lista[0]))
print(type(minha_lista[1]))
print(type(minha_lista[2]))
print(type(minha_lista[3]))

[1, 1.0, (1+0j), '1']
1 1.0 (1+0j) 1
<class 'int'>
<class 'float'>
<class 'complex'>
<class 'str'>


In [34]:
tua_lista = []
print(tua_lista)

tua_lista.append(7)
print(tua_lista)

tua_lista.append(11)
print(tua_lista)

tua_lista.append(15)
print(tua_lista)

tua_lista.append(2)
print(tua_lista)

tua_lista.remove(11)
print(tua_lista)

[]
[7]
[7, 11]
[7, 11, 15]
[7, 11, 15, 2]
[7, 15, 2]


In [36]:
print(len(tua_lista))
print(min(tua_lista), max(tua_lista))
tua_lista.sort()
print(tua_lista)

3
2 15
[2, 7, 15]


In [45]:
tua_tupla = (1, 2, 1, 1)  # tua_tupla(1, 2, 1, 1)
print(tua_tupla)

print(tua_tupla.count(1))
print(tua_tupla.count(2))

print(tua_tupla.index(1))
print(tua_tupla.index(2))

print(min(tua_tupla), max(tua_tupla))

(1, 2, 1, 1)
3
1
0
1
1 2


In [53]:
meu_conjunto = {1, 1, "a", "a"}

print(meu_conjunto)
print(type(meu_conjunto))

print(type(list(meu_conjunto)[0]))

{1, 'a'}
<class 'set'>
<class 'int'>


In [58]:
b = list(range(10))
print(b)
print(type(b))

b = list(range(0, 10, 2))
print(b)

b = list(range(1, 11))
print(d)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
<class 'list'>
[0, 2, 4, 6, 8]
1


In [7]:
import numpy as np
A = np.array([1, 2, 3])
print(A)
print(type(A))
print(dir(A))

print(A.ndim)
print(A.shape)
print(A.size)
print(A.dtype)
print(A.itemsize)
print(A.data)

[1 2 3]
<class 'numpy.ndarray'>
['T', '__abs__', '__add__', '__and__', '__array__', '__array_finalize__', '__array_function__', '__array_interface__', '__array_prepare__', '__array_priority__', '__array_struct__', '__array_ufunc__', '__array_wrap__', '__bool__', '__class__', '__complex__', '__contains__', '__copy__', '__deepcopy__', '__delattr__', '__delitem__', '__dir__', '__divmod__', '__doc__', '__eq__', '__float__', '__floordiv__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__gt__', '__hash__', '__iadd__', '__iand__', '__ifloordiv__', '__ilshift__', '__imatmul__', '__imod__', '__imul__', '__index__', '__init__', '__init_subclass__', '__int__', '__invert__', '__ior__', '__ipow__', '__irshift__', '__isub__', '__iter__', '__itruediv__', '__ixor__', '__le__', '__len__', '__lshift__', '__lt__', '__matmul__', '__mod__', '__mul__', '__ne__', '__neg__', '__new__', '__or__', '__pos__', '__pow__', '__radd__', '__rand__', '__rdivmod__', '__reduce__', '__reduce_ex__', '__repr_

In [9]:
for a in A.data:
    print(a)

1
2
3


In [11]:
print(A[0], A[1], A[0])
print(A[-1])

1 2 1
3


In [16]:
print(A[1:3])
print(A[::-1])

[2 3]
[3 2 1]


In [17]:
B = np.array([[1,2,3],[4,5,6]], dtype=np.float32)
print(B)

[[1. 2. 3.]
 [4. 5. 6.]]


In [19]:
print(B.ndim)
print(B.shape)

2
(2, 3)


In [27]:
print(B[0])
print(B[1])
print(B[0, 0], B[0,1])
print(B[0:2, 0:2])

[1. 2. 3.]
[4. 5. 6.]
1.0 2.0
[[1. 2.]
 [4. 5.]]


In [33]:
C = np.ndarray([1,2,3])
print(C)

[[[2.62534641e+179 2.57893715e-057 1.36372786e+161]
  [1.74417268e-076 4.10450009e-307 1.33360330e+241]]]


In [34]:
A = np.zeros((3,2), dtype=np.complex64)
print(A)

[[0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j]]


In [36]:
D = np.arange(0,20,5)
print(D)

[ 0  5 10 15]


In [38]:
E = np.arange(0,1,0.1)
print(E)

[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]


In [39]:
F = np.linspace(0,1,9)
print(F)

[0.    0.125 0.25  0.375 0.5   0.625 0.75  0.875 1.   ]


In [42]:
x = np.linspace(0, 2 * np.pi, 10)
y = np.sin(x)

print(x)
print(y)

print(list(zip(x,y)))

[0.         0.6981317  1.3962634  2.0943951  2.7925268  3.4906585
 4.1887902  4.88692191 5.58505361 6.28318531]
[ 0.00000000e+00  6.42787610e-01  9.84807753e-01  8.66025404e-01
  3.42020143e-01 -3.42020143e-01 -8.66025404e-01 -9.84807753e-01
 -6.42787610e-01 -2.44929360e-16]
[(0.0, 0.0), (0.6981317007977318, 0.6427876096865393), (1.3962634015954636, 0.984807753012208), (2.0943951023931953, 0.8660254037844387), (2.792526803190927, 0.3420201433256689), (3.490658503988659, -0.34202014332566866), (4.1887902047863905, -0.8660254037844384), (4.886921905584122, -0.9848077530122081), (5.585053606381854, -0.6427876096865396), (6.283185307179586, -2.4492935982947064e-16)]


In [43]:
a = np.array([10,20,30,40])
print(a)

b = np.arange(4)
print(b)

c = a - b
print(c)

[10 20 30 40]
[0 1 2 3]
[10 19 28 37]


In [44]:
def f(x):
    y = 5*x+2
    return y

In [45]:
x = list(range(10))
y = []

In [47]:
for i in x:
    y.append(f(i))
    
print(list(zip(x, y)))

x = np.arange(0, 10)
y = 5*x+2

print(list(zip(x, y)))

[(0, 2), (1, 7), (2, 12), (3, 17), (4, 22), (5, 27), (6, 32), (7, 37), (8, 42), (9, 47)]
[(0, 2), (1, 7), (2, 12), (3, 17), (4, 22), (5, 27), (6, 32), (7, 37), (8, 42), (9, 47)]


In [57]:
import numpy
A = np.array([[1,1], [0,1]])
print(A)

B = np.array([[2,0],[3,4]])
print(B)

print(B.T)  #Transporte

print(numpy.linalg.det(A))

[[1 1]
 [0 1]]
[[2 0]
 [3 4]]
[[2 3]
 [0 4]]
1.0


In [73]:
A = np.random.rand(3, 2)
print(A)
print(round(A.sum(), 2), round(A.mean(),2))
print(round(A.min(), 2), round(A.max(), 2))

print(A.sum(axis=0))


[[0.53346228 0.36246451]
 [0.74257379 0.11919202]
 [0.21527168 0.70351157]]
2.68 0.45
0.12 0.74
[1.49130775 1.1851681 ]


In [75]:
A =  np.array([1,2,3,4])
print(A)

for elemento in A:
    print (elemento)

[1 2 3 4]
1
2
3
4


In [76]:
for i in range(A.shape[0]):
    print(A[i])

1
2
3
4


In [4]:
import numpy as np
A = np.array([1,2,3,4])
print(A)

B = A    # Não cria uma cópia, apenas faz uma referência
B[0] = 10

print(B)
print(A)

B = A.copy()
B[3] = 20
print(B)
print(A)

del A

[1 2 3 4]
[10  2  3  4]
[10  2  3  4]
[10  2  3 20]
[10  2  3  4]
